# CSL7620 :: Machine Learning

# Programming Assignment 0.1

**Name:**  
**Roll Number:**  

# Python Warmup
- **100 points**
- **Due 17th August Sunday by 11:59 pm**

This assignment tests the basics of Python, NumPy, and Pandas, essential for implementing machine learning algorithms. The assignment consists of 15 coding questions of varying difficulty levels, from easy to medium. You are required to complete the functions defined in the code blocks following each question. You only need to fill out sections of the code marked `"YOUR CODE HERE"`. Do **NOT** modify the test cases provided, as we will use them to grade your solutions. Once you've filled out your solutions, submit the notebook (select from drive) on Classroom. Do **NOT** forget to type in your name and Roll Number at the beginning of the notebook.

## Tutorial on Jupyter Notebooks

If you are new to Jupyter Notebooks, you can find more information on how to use them [here](https://realpython.com/jupyter-notebook-introduction/).



###***`You are expected to complete this assignment independently, without using any tools such as ChatGPT, other AI assistance, or external resources. This will be beneficial for your own learning and development.`***

## Python Basics


###Question 1 (5 points)

Complete the function reverse_string to return the reversed version of a given string. Ignore case and spaces.

In [ ]:
def reverse_string(s: str) -> str:
    # YOUR CODE HERE
    pass

# Test cases
print(reverse_string("Hello World"))  # Expected: "dlrowolleh"
print(reverse_string("Python"))       # Expected: "nohtyp"


None
None


###Question 2 (5 points)
Complete the function exponentiate_list that raises each element in the list to the power of its index and returns a new list.

Example:
Given list: [1, 3, 5, 7]
New list: [1, 3, 25, 343]

In [ ]:
def exponentiate_list(lst: list) -> list:
    # YOUR CODE HERE
    pass

# Test cases
print(exponentiate_list([1, 3, 5, 7]))  # Expected: [1, 3, 25, 343]
print(exponentiate_list([2, 0, 4, 1]))  # Expected: [1, 0, 16, 1]

None
None


###Question 3 (10 points)
Complete the function array_stats that returns the mean, median, and standard deviation of a NumPy array.

In [ ]:
import numpy as np

def array_stats(arr: np.ndarray) -> tuple:
    # YOUR CODE HERE
    pass

# Test cases
print(array_stats(np.array([1, 2, 3, 4, 5])))  # Expected: (3.0, 3.0, 1.4142135623730951)
print(array_stats(np.array([10, 20, 30, 40, 50])))  # Expected: (30.0, 30.0, 14.142135623730951)


None
None


###Question 4 (5 points)
Complete the function matrix_reshape to reshape a given matrix to the target dimensions n_rows and n_cols.

In [ ]:
def matrix_reshape(matrix: np.ndarray, n_rows: int, n_cols: int) -> np.ndarray:
    # YOUR CODE HERE

    pass

# Test cases
print(matrix_reshape(np.array([[1, 2], [3, 4]]), 1, 4))  # Expected: [[1, 2, 3, 4]]
print(matrix_reshape(np.array([[1, 2, 3], [4, 5, 6]]), 3, 2))  # Expected: [[1, 2], [3, 4], [5, 6]]


None
None


###Question 5 (5 points)
Complete the function elementwise_product that returns the element-wise product of two matrices.

In [ ]:
def elementwise_product(mat1: np.ndarray, mat2: np.ndarray) -> np.ndarray:
    # YOUR CODE HER
    pass

# Test cases
print(elementwise_product(np.array([[1, 2], [3, 4]]), np.array([[2, 0], [1, 3]])))  # Expected: [[2, 0], [3, 12]]
print(elementwise_product(np.array([[5, 6], [7, 8]]), np.array([[1, 2], [3, 4]])))  # Expected: [[5, 12], [21, 32]]


None
None


###Question 6 (5 points)
Complete the function matrix_determinant that computes the determinant of a matrix.

In [ ]:
def matrix_determinant(matrix: np.ndarray) -> float:
    # YOUR CODE HERE
    pass

# Test cases
print(matrix_determinant(np.array([[1, 2], [3, 4]])))  # Expected: -2.0
print(matrix_determinant(np.array([[2, 5], [1, 3]])))  # Expected: 1.0


None
None


###Question 7 (5 points)
Complete the function normalize_matrix that normalizes each element of a matrix by the maximum element in the matrix.

In [ ]:
def normalize_matrix(matrix: np.ndarray) -> np.ndarray:
     # YOUR CODE HERE
    pass

# Test cases
print(normalize_matrix(np.array([[1, 2], [3, 4]])))  # Expected: [[0.25, 0.5], [0.75, 1.0]]
print(normalize_matrix(np.array([[5, 10], [15, 20]])))  # Expected: [[0.25, 0.5], [0.75, 1.0]]


None
None


###Question 8 (10 points)
Complete the function subtract_row_mean that subtracts the mean of each row from each element in that row of a matrix.

In [ ]:
def subtract_row_mean(matrix: np.ndarray) -> np.ndarray:
    # YOUR CODE HERE
    pass

# Test cases
print(subtract_row_mean(np.array([[1, 2, 3], [4, 5, 6]])))  # Expected: [[-1, 0, 1], [-1, 0, 1]]
print(subtract_row_mean(np.array([[7, 8, 9], [10, 11, 12]])))  # Expected: [[-1, 0, 1], [-1, 0, 1]]


[[-1.  0.  1.]
 [-1.  0.  1.]]
[[-1.  0.  1.]
 [-1.  0.  1.]]


###Question 9 (10 points)
Complete the function sliding_window_average that computes the average over a sliding window of size window_size for a 1-D array.

In [ ]:
def sliding_window_average(arr: np.ndarray, window_size: int) -> np.ndarray:
    # YOUR CODE HERE
    pass

# Test cases
print(sliding_window_average(np.array([1, 2, 3, 4, 5]), 3))  # Expected: [2.0, 3.0, 4.0]
print(sliding_window_average(np.array([10, 20, 30, 40, 50]), 2))  # Expected: [15.0, 25.0, 35.0, 45.0]


None
None


##Pandas Basics


The provided data contains information about various products sold over a period of time.

Data Description
* ProductID: Unique ID of the product
* Category: Product category
* Price: Price of the product
* Sales_Day1: Sales on Day 1
* Sales_Day2: Sales on Day 2
* Sales_Day3: Sales on Day 3
* Vendor: Vendor of the product

###Question 10 (5 points)
Compute the number of unique product categories in df.

In [ ]:
import pandas as pd

def unique_categories(df: pd.DataFrame) -> int:
    # YOUR CODE HERE
    pass

# Test cases
df_test = pd.DataFrame({
    'ProductID': [1, 2, 3, 4],
    'Category': ['A', 'B', 'A', 'C'],
    'Price': [10, 20, 15, 30],
    'Sales_Day1': [100, 200, 150, 300],
    'Sales_Day2': [110, 210, 160, 310],
    'Sales_Day3': [120, 220, 170, 320],
    'Vendor': ['X', 'Y', 'X', 'Z']
})
print(unique_categories(df_test))  # Expected: 3


None


###Question 11 (5 points)
Calculate the number of products sold by the vendor VendorA.

In [ ]:
def count_vendor_products(df: pd.DataFrame, vendor: str) -> int:
    # YOUR CODE HERE
    pass

# Test cases
df_test = pd.DataFrame({
    'ProductID': [1, 2, 3, 4],
    'Category': ['A', 'B', 'A', 'C'],
    'Price': [10, 20, 15, 30],
    'Sales_Day1': [100, 200, 150, 300],
    'Sales_Day2': [110, 210, 160, 310],
    'Sales_Day3': [120, 220, 170, 320],
    'Vendor': ['VendorA', 'VendorB', 'VendorA', 'VendorC']
})
print(count_vendor_products(df_test, 'VendorA'))  # Expected: 2


None


###Question 12 (5 points)
List the product categories sold by VendorB.

In [ ]:
def vendor_categories(df: pd.DataFrame, vendor: str) -> list:
    # YOUR CODE HERE
    pass

# Test cases
df_test = pd.DataFrame({
    'ProductID': [1, 2, 3, 4],
    'Category': ['A', 'B', 'A', 'C'],
    'Price': [10, 20, 15, 30],
    'Sales_Day1': [100, 200, 150, 300],
    'Sales_Day2': [110, 210, 160, 310],
    'Sales_Day3': [120, 220, 170, 320],
    'Vendor': ['VendorA', 'VendorB', 'VendorA', 'VendorC']
})
print(vendor_categories(df_test, 'VendorB'))  # Expected: ['B']


None


###Question 13 (5 points)
Calculate the total number of missing values (they are NaN) in df.

In [ ]:
def count_missing_values(df: pd.DataFrame) -> int:
    # YOUR CODE HERE
    pass

# Test cases
df_test = pd.DataFrame({
    'ProductID': [1, 2, 3, 4, None],
    'Category': ['A', 'B', 'A', 'C', 'D'],
    'Price': [10, 20, 15, 30, None],
    'Sales_Day1': [100, 200, 150, 300, None],
    'Sales_Day2': [110, 210, 160, 310, None],
    'Sales_Day3': [120, 220, 170, 320, None],
    'Vendor': ['VendorA', 'VendorB', 'VendorA', 'VendorC', None]
})
print(count_missing_values(df_test))  # Expected: 6


None


###Question 14 (10 points)
Calculate the average sales (ignoring NaN values) for all the products. Then modify df by replacing all the NaN values in Sales_Day1, Sales_Day2, and Sales_Day3 columns with the average sales.

In [ ]:
def average_sales(df: pd.DataFrame) -> float:
    # YOUR CODE HERE
    pass

def fill_missing_sales(df: pd.DataFrame) -> pd.DataFrame:
    # YOUR CODE HERE
    pass

# Test cases
df_test = pd.DataFrame({
    'ProductID': [1, 2, 3, 4, None],
    'Category': ['A', 'B', 'A', 'C', 'D'],
    'Price': [10, 20, 15, 30, None],
    'Sales_Day1': [100, 200, 150, 300, None],
    'Sales_Day2': [110, 210, 160, 310, None],
    'Sales_Day3': [120, 220, 170, 320, None],
    'Vendor': ['VendorA', 'VendorB', 'VendorA', 'VendorC', None]
})
average = average_sales(df_test)
print(average)  # Expected: 197.5
df_filled = fill_missing_sales(df_test)
print(df_filled)


None
None


###Question 15 (10 points)
Some values in the ProductID column are missing (NaN). These IDs should increase sequentially. Fill in these missing IDs and make the column an integer column (instead of a float column).

In [ ]:
def fill_product_ids(df: pd.DataFrame) -> pd.DataFrame:
    # YOUR CODE HERE
    pass

# Test cases
df_test = pd.DataFrame({
    'ProductID': [1001, None, 1003, None],
    'Category': ['A', 'B', 'A', 'C'],
    'Price': [10, 20, 15, 30],
    'Sales_Day1': [100, 200, 150, 300],
    'Sales_Day2': [110, 210, 160, 310],
    'Sales_Day3': [120, 220, 170, 320],
    'Vendor': ['VendorA', 'VendorB', 'VendorA', 'VendorC']
})
df_filled = fill_product_ids(df_test)
print(df_filled)
# Expected ProductID column: [1001, 1002, 1003, 1004]


None
